project:
  type: website
  output-dir: docs

website:
  title: "Historic Zoning Maps"
  #navbar:
  sidebar:
    style: "floating"
    search: false
    contents:
      - href: index.qmd
        text: Maps
      - href: dashboard.qmd
        text: Dashboard
  page-footer: 
    border: true
    left:
      - icon: github
        href: https://github.com/nchiumenti/historic-zoning-map
        aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    grid:
      sidebar-width: 150px
      body-width: 2000px
      margin-width: 150px
